apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-minio
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-minio
  template:
    metadata:
      labels:
        app: mlflow-minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-07-27T18-37-02Z
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ACCESS_KEY
          value: minioadmin
        - name: MINIO_SECRET_KEY
          value: minioadmin
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-storage
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-minio-service
  namespace: ml
spec:
  selector:
    app: mlflow-minio
  ports:
  - port: 9000
    targetPort: 9000
  - port: 9001
    targetPort: 9001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-pvc
  namespace: ml
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
