
image:
  repository: mnist-api
  tag: local
  pullPolicy: IfNotPresent
replicaCount: 1
revisionHistoryLimit: 3
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: "200m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "4Gi"
env: []
