apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
  namespace: ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/matthijskeep/mlflow-s3:v1
        command:
        - mlflow
        - server
        args:
        - --host
        - 0.0.0.0
        - --port
        - "5000"
        - --backend-store-uri
        - "postgresql://mlflow:mlflow@mlflow-postgres-service:5432/mlflow"
        - --default-artifact-root
        - "s3://mlflow-bucket/"
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://mlflow-minio-service.ml.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: minioadmin
        - name: AWS_SECRET_ACCESS_KEY
          value: minioadmin
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: ml
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
