
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-api
  labels:
    app: mnist-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mnist-api
  template:
    metadata:
      labels:
        app: mnist-api
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: FEAST_REPO_PATH
              value: /app/features/feast_repo
            - name: REDIS_HOST
              value: redis.{{ .Release.Namespace }}.svc.cluster.local
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
