
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-api
  labels:
    app: mnist-api
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels:
      app: mnist-api
  template:
    metadata:
      labels:
        app: mnist-api
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: FEAST_REPO_PATH
              value: /app/features/feast_repo
            - name: REDIS_HOST
              value: redis-master.{{ .Release.Namespace }}.svc.cluster.local
            - name: REDIS_PASSWORD
              value: redispw #probably not the best way to do this in production
            - name: MLFLOW_TRACKING_URI
              value: "http://host.minikube.internal:5000"
            - name: MINIO_ENDPOINT_URL
              value: "http://host.minikube.internal:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MODEL_URI
              value: "models:/mnist_cnn_model/1"
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 240
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 3
