
apiVersion: v1
kind: Service
metadata:
  name: mnist-api
  labels:
    app: mnist-api
spec:
  selector:
    app: mnist-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
