
name: ci-cd
on:
  push:
    branches: ['main', 'feature/*']
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install UV
        uses: astral-sh/setup-uv@v6
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run ruff
        uses: astral-sh/ruff-action@v3
#  Other jobs still to be defined.
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #     - name: Build images (multi-arch)
  #       uses: docker/setup-qemu-action@v3
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build & push api
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: Dockerfile.api
  #         push: true
  #         tags: ghcr.io/${{ github.repository }}/mnist-api:${{ github.sha }}
  #         platforms: linux/amd64,linux/arm64
  # # Deploy job would require cluster auth; left as an exercise for local kind
